# 3_5 choose_learning_machine_models with UPSAMPLING

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#load the file 
data = pd.read_csv('../data/cleaned_data/cleaned_data.csv')
data.head()

,senior_citizen,partner,dependents,phone_service,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,...,internet_service_Fiber optic,internet_service_No,contract_Month-to-month,contract_One year,contract_Two year,payment_method_Bank transfer (automatic),payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,churn
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,1,0,No
1,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,No
2,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,0,1,Yes
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0,0,0,1,0,1,0,0,0,No
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,1,0,0,0,0,1,0,Yes

In [3]:
data.shape

(7032, 26)

### x/y split

In [4]:
#separate the features from the labels
y = data['churn']
X = data.drop(['churn'], axis=1)

In [5]:
# change the type of 'y'
y.dtypes

dtype('O')

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
display(y_train.value_counts())
display(y_test.value_counts())

churn
No     4130
Yes    1495
Name: count, dtype: int64

churn
No     1033
Yes     374
Name: count, dtype: int64

#### It is imbalanced,so it needs up/down sampling or SMOTE

In [15]:
df = pd.concat([X_train, y_train], axis=1)
df.head()

,senior_citizen,partner,dependents,phone_service,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,...,internet_service_Fiber optic,internet_service_No,contract_Month-to-month,contract_One year,contract_Two year,payment_method_Bank transfer (automatic),payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,churn
6021,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0,0,1,0,0,1,0,0,0,Yes
3404,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,1,0,0,0,1,0,0,Yes
5474,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,0,1,0,Yes
5515,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0,0,0,0,1,1,0,0,0,No
6328,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1,0,0,1,0,0,0,0,1,No

In [14]:
from sklearn.utils import resample


df_majority = df[df['churn'] == "No"]
df_minority = df[df['churn'] == "Yes"]

df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                 n_samples=len(df_majority),    # to match majority class
                                 random_state=123) # reproducible results
data1 = pd.concat([df_majority, df_minority_upsampled], axis=0)
data1.shape

(8260, 26)

In [18]:
y_resampled = data1['churn']
X_resampled = data1.drop(['churn'], axis=1)

In [25]:
X_resampled

,senior_citizen,partner,dependents,phone_service,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,...,internet_service_DSL,internet_service_Fiber optic,internet_service_No,contract_Month-to-month,contract_One year,contract_Two year,payment_method_Bank transfer (automatic),payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check
5515,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1,0,0,0,0,1,1,0,0,0
6328,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0,1,0,0,1,0,0,0,0,1
6755,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,1,0,0,0,0,1
6914,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,1,0,0,0,0,1
1671,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6065,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,0,1,0,0,0,0,1,0
2241,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,0,1,0,1,0,0,0,0,1,0
2999,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,1,0,1,0,0,0,0,0,1
3837,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,1,0,0,0,1,0,0,1,0,0
2202,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0,1,0,1,0,0,0,0,1,0

In [26]:
y_resampled

5515     No
6328     No
6755     No
6914     No
1671     No
       ...
6065    Yes
2241    Yes
2999    Yes
3837    Yes
2202    Yes
Name: churn, Length: 8260, dtype: object

In [19]:
X_resampled.shape

(8260, 25)

In [20]:
class_counts = y_resampled.value_counts()
print(class_counts)

churn
No     4130
Yes    4130
Name: count, dtype: int64

In [21]:
# save 
X_resampled.to_csv('../data/x_y_data/SMOTE/up_X_resampled.csv', index=False)
y_resampled.to_csv('../data/x_y_data/SMOTE/up_y_resampled.csv', index=False)
X_test.to_csv('../data/x_y_data/SMOTE/up_X_test.csv', index=False)
y_test.to_csv('../data/x_y_data/SMOTE/up_y_test.csv', index=False)