# 3_6 choose_learning_machine_models with DOWNSAMPLING

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#load the file 
data = pd.read_csv('../data/cleaned_data/cleaned_data.csv')
data.head()

,senior_citizen,partner,dependents,phone_service,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,...,internet_service_Fiber optic,internet_service_No,contract_Month-to-month,contract_One year,contract_Two year,payment_method_Bank transfer (automatic),payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,churn
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,1,0,No
1,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,No
2,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,0,1,Yes
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0,0,0,1,0,1,0,0,0,No
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,1,0,0,0,0,1,0,Yes

In [3]:
data.shape

(7032, 26)

### x/y split

In [4]:
#separate the features from the labels
y = data['churn']
X = data.drop(['churn'], axis=1)

In [5]:
# change the type of 'y'
y.dtypes

dtype('O')

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
display(y_train.value_counts())
display(y_test.value_counts())

churn
No     4130
Yes    1495
Name: count, dtype: int64

churn
No     1033
Yes     374
Name: count, dtype: int64

#### It is imbalanced,so it needs up/down sampling or SMOTE

In [9]:
df = pd.concat([X_train, y_train], axis=1)
df.head()

,senior_citizen,partner,dependents,phone_service,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,...,internet_service_Fiber optic,internet_service_No,contract_Month-to-month,contract_One year,contract_Two year,payment_method_Bank transfer (automatic),payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,churn
6021,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0,0,1,0,0,1,0,0,0,Yes
3404,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,1,0,0,0,1,0,0,Yes
5474,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1,0,1,0,0,0,0,1,0,Yes
5515,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0,0,0,0,1,1,0,0,0,No
6328,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1,0,0,1,0,0,0,0,1,No

In [10]:
from sklearn.utils import resample

df_majority = df[df['churn'] == "No"]
df_minority = df[df['churn'] == "Yes"]

df_majority_downsampled = resample(df_majority,
                                    replace=False,     # sample without replacement
                                    n_samples=len(df_minority),    # to match minority class
                                    random_state=123) # reproducible results
data1 = pd.concat([df_majority_downsampled, df_minority], axis=0)
data1.shape

(2990, 26)

In [11]:
y_resampled = data1['churn']
X_resampled = data1.drop(['churn'], axis=1)

In [12]:
X_resampled

,senior_citizen,partner,dependents,phone_service,multiple_lines,online_security,online_backup,device_protection,tech_support,streaming_tv,...,internet_service_DSL,internet_service_Fiber optic,internet_service_No,contract_Month-to-month,contract_One year,contract_Two year,payment_method_Bank transfer (automatic),payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check
5742,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,1,0,1,0,0
2967,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1,0,0,0,0,1,0,1,0,0
3728,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0,1,0,0,0,1,1,0,0,0
2192,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,1,0,0,1,0,0,0,0,1,0
6683,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2433,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,...,0,1,0,1,0,0,1,0,0,0
769,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,1,0,1,0,0,0,0,1,0
2919,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,1,0,0,0,0,1,0
6231,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,1,0,1,0,0,0,0,1,0
860,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,0,1,0,0,0,0,1,0

In [13]:
y_resampled

5742     No
2967     No
3728     No
2192     No
6683     No
       ...
2433    Yes
769     Yes
2919    Yes
6231    Yes
860     Yes
Name: churn, Length: 2990, dtype: object

In [14]:
X_resampled.shape

(2990, 25)

In [15]:
class_counts = y_resampled.value_counts()
print(class_counts)

churn
No     1495
Yes    1495
Name: count, dtype: int64

In [16]:
# save 
X_resampled.to_csv('../data/x_y_data/SMOTE/down_X_resampled.csv', index=False)
y_resampled.to_csv('../data/x_y_data/SMOTE/down_y_resampled.csv', index=False)
X_test.to_csv('../data/x_y_data/SMOTE/down_X_test.csv', index=False)
y_test.to_csv('../data/x_y_data/SMOTE/down_y_test.csv', index=False)

### Choosing models

In [22]:
X_resampled.shape

(8260, 25)

In [29]:
y_resampled =pd.DataFrame(y_resampled)

y_resampled.loc[y_resampled['churn'] == 'Yes', 'churn'] = 1
y_resampled.loc[y_resampled['churn'] == 'No', 'churn'] = 0

y_resampled['churn'] =y_resampled['churn'].astype('int64')

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier


models = []
models.append(('LR', LogisticRegression(random_state = 12345)))
models.append(('KNN', KNeighborsClassifier()))
models.append(('RF', RandomForestClassifier(random_state = 12345)))
models.append(('GB', GradientBoostingClassifier(random_state = 12345)))

#### Kappa

In [31]:
# evaluate each model in turn
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import cohen_kappa_score, make_scorer

import warnings
warnings.filterwarnings('ignore')

X_resampled2 = np.ascontiguousarray(X_resampled)
y_resampled2 = np.ascontiguousarray(y_resampled)


kappa_scorer = make_scorer(cohen_kappa_score)

names = []
results = []

for name, model in models:
    kfold = KFold(n_splits=10, shuffle=False)
    cv_results = cross_val_score(model, X_resampled2, y_resampled2, cv=kfold, scoring=kappa_scorer)
    results.append(cv_results)
    names.append(name)
    msg = f"{name}: {cv_results.mean()} ({cv_results.std()})"
    print(msg)

LR: 0.0 (0.0)
KNN: 0.0 (0.0)
RF: 0.0 (0.0)
GB: 0.0 (0.0)

In [ ]:
# boxplot algorithm comparison
fig = plt.figure(figsize=(15,10))
fig.suptitle('Algorithm Comparison')
ax = fig.add_subplot(111)
plt.boxplot(results)
ax.set_xticklabels(names)
plt.show()

In [ ]:
results_dict = {name: result for name, result in zip(names, results)}

# Create the DataFrame using the dictionary
score = pd.DataFrame(results_dict)

# Print the DataFrame
display(score)